Repository aws-solutions/aws-media-services-application-mapper, pull requests merged in 2022-03, with the labels that each got.

#314 Bump urijs from 1.19.8 to 1.19.10
  source/html/package-lock.json
Labels: dependencies

#318 Dependency update for UI
  source/html/package-lock.json
  source/html/package.json
Labels: build-and-deploy

#322 Changes for various SQ issues
  source/html/js/app/alarms.js
  source/html/js/app/channels.js
  source/html/js/app/cloudwatch_events.js
  source/html/js/app/events.js
  source/html/js/app/mappers/connections/cloudfront_medialive_input.js
  source/html/js/app/mappers/connections/link_device_medialive_input.js
  source/html/js/app/mappers/connections/mediaconnect_flow_mediaconnect_flow.js
  source/html/js/app/mappers/connections/mediaconnect_flow_medialive_input.js
  source/html/js/app/mappers/connections/medialive_channel_input.js
  source/html/js/app/mappers/connections/medialive_channel_mediaconnect_flow.js
  source/html/js/app/mappers/connections/medialive_channel_mediapackage_channel.js
  source/html/js/app/mappers/connections/medialive_channel_mediastore_container.js
  source/html/js/app/mappers/connections/medialive_channel_multiplex.js
  source/html/js/app/mappers/connections/medialive_channel_s3_bucket.js
  source/html/js/app/mappers/connections/medialive_input_channel.js
  source/html/js/app/mappers/connections/mediapackage_channel_endpoint.js
  source/html/js/app/mappers/connections/mediapackage_endpoint_cloudfront.js
  source/html/js/app/mappers/connections/mediapackage_endpoint_mediatailor_configuration.js
  source/html/js/app/mappers/connections/mediastore_container_cloudfront.js
  source/html/js/app/mappers/connections/mediastore_container_medialive_input.js
  source/html/js/app/mappers/connections/mediastore_container_mediatailor_configuration.js
  source/html/js/app/mappers/connections/multiplex_mediaconnect_flow.js
  source/html/js/app/mappers/connections/s3_bucket_cloudfront.js
  source/html/js/app/mappers/connections/s3_bucket_medialive_input.js
  source/html/js/app/mappers/connections/s3_bucket_mediatailor_configuration.js
  source/html/js/app/mappers/connections/speke.js
  source/html/js/app/mappers/connections/user_defined_connection.js
  source/html/js/app/mappers/nodes/cloudfront.js
  source/html/js/app/mappers/nodes/ec2.js
  source/html/js/app/mappers/nodes/mediaconnect.js
  source/html/js/app/mappers/nodes/medialive.js
  source/html/js/app/mappers/nodes/mediatailor.js
  source/html/js/app/mappers/nodes/ssm_managed_instance.js
  source/html/js/app/ui/alarm_indicators.js
  source/html/js/app/ui/alarms_menu.js
  source/html/js/app/ui/diagram_factory.js
  source/html/js/app/ui/diagram_statemachine_factory.js
  source/html/js/app/ui/diagrams.js
  source/html/js/app/ui/event_alert_indicators.js
  source/html/js/app/ui/monitor_view.js
  source/html/js/app/ui/search_view.js
  source/html/js/app/ui/selected_item_view.js
  source/html/js/app/ui/settings_menu.js
  source/html/js/app/ui/svg_node.js
  source/html/js/app/ui/tile_view.js
  source/html/js/app/ui/user_defined.js
  source/tools/js-check.sh
Labels: front-end

#325 Tile enhancements
  source/html/index.html
  source/html/js/app/mappers/connections/user_defined_connection.js
  source/html/js/app/mappers/nodes/mediapackage.js
  source/html/js/app/mappers/nodes/mediastore.js
  source/html/js/app/mappers/nodes/s3.js
  source/html/js/app/search.js
  source/html/js/app/server.js
  source/html/js/app/tools/build_numbers.js
  source/html/js/app/ui/channels_menu.js
  source/html/js/app/ui/diagram_statemachine_factory.js
  source/html/js/app/ui/diagrams.js
  source/html/js/app/ui/help_menu.js
  source/html/js/app/ui/selected_item_view.js
  source/html/js/app/ui/tile_view.js
  source/html/package-lock.json
Labels: enhancement, visualization feature, front-end

#326 Initial UI changes for #55
  source/html/index.html
  source/html/js/app/notes.js
  source/html/js/app/statemachine.js
  source/html/js/app/ui/notes_view.js
  source/html/js/app/ui/selected_item_view.js
  source/html/package-lock.json
  source/html/package.json
  source/msam/app.py
  source/msam/chalicelib/notes.py
Labels: front-end
